Update browserslist so that browser ranges work
Browserslist 0.3.3 complains about (some?) browser ranges: 

    Error: Unknown browser query `ios_saf 8.1-8.4`

0.5.0 does not seem to have this problem.